name: Deploy Sphinx documentation to Pages

on:
  push:
    branches:
    - documentation
    tags:
    - docs-*

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - id: deployment
      uses: sphinx-notes/pages@v3
      # https://github.com/sphinx-notes/pages
      with:
        documentation_path: ./docs/source
        requirements_path: ./docs/source/requirements.txt
        pyproject_extras: ""
